server:
  port: 8083
feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090 #sentinel控制台链接地址
      http-method-specify: true #是否设置请求方式作为资源名称
hm:
  db:
    database: hm-user
  swagger:
    title: "黑马商城用户服务接口文档"
    package: com.hmall.user.controller
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
      - /hi
# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123